
version: "3"
services:
  eureka:
    build:
      context: ./eureka/
      dockerfile: Dockerfile
    networks:
      - ribastore-network
    ports:
      - "8761:8761"
  configuration:
    build:
      context: ./configuration/
      dockerfile: Dockerfile
    networks:
      - ribastore-network
    ports:
      - "8888:8888"
  mysql-delivery:
    image: mysql:8
    networks:
      - ribastore-network
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=delivery
    ports:
      - "3306:3306"
  delivery:
    build:
      context: ./ribastore-delivery/
      dockerfile: Dockerfile
    networks:
      - ribastore-network
    environment:
      - CONFIG_HOST=configuration
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8083:8083"
    restart: on-failure
    depends_on:
      - mysql-delivery
      - configuration
      - eureka
    links:
      - mysql-delivery
      - configuration
      - eureka
networks:
  ribastore-network:
    driver: bridge