
version: "3"
services:
    eureka:
        build:
          context: ./eureka/
          dockerfile: Dockerfile
        networks:
          - ribastore-network
        ports:
          - "8761:8761"
    configuration:
        build:
          context: ./configuration/
          dockerfile: Dockerfile
        networks:
          - ribastore-network
        ports:
          - "8888:8888"
    authentication:
        build:
          context: ./authentication/
          dockerfile: Dockerfile
        networks:
          - ribastore-network
        ports:
          - "8088:8088"
    mysql-ribastore:
        image: mysql:8
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        networks:
          - ribastore-network
        restart: always
        volumes: 
            - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
        ports:
          - "3306:3306"
    delivery:
        build:
          context: ./ribastore-delivery/
          dockerfile: Dockerfile
        networks:
          - ribastore-network
        environment:
          - CONFIG_HOST=configuration
          - EUREKA_HOST=eureka
          - SPRING_PROFILES_ACTIVE=docker
        ports:
          - "8083:8083"
        restart: on-failure
        depends_on:
          - mysql-ribastore
            - condition=service_healthy
          - configuration
            - condition=service_healthy
          - eureka
        links:
          - mysql-ribastore
          - configuration
          - eureka
    estoque:
        build:
          context: ./ribastore-estoque/
          dockerfile: Dockerfile
        networks:
          - ribastore-network
        environment:
          - CONFIG_HOST=configuration
          - EUREKA_HOST=eureka
          - OAUTH2_HOST=authentication
          - SPRING_PROFILES_ACTIVE=docker
        ports:
          - "8081:8081"
        restart: on-failure
        depends_on:
          - mysql-ribastore
            -condition=service_healthy
          - configuration
            -condition=service_healthy
          - authentication
          - eureka
        links:
          - mysql-ribastore
          - configuration
          - authentication
          - eureka
networks:
  ribastore-network:
    driver: bridge