
server:  port: 8080
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka


security:
  oauth2:
    resource:
      user-info-uri: http://${OAUTH2_HOST}:8088/user

hystrix:  shareSecurityContext: true
  
logging:
  level:
    com:
      ribastore:
        loja:
          client: DEBUG